server:
  port: 8082
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.137.53.253:3306/hundsun02?characterEncoding=utf8&serverTimezone=GMT%2b8
    username: hundsun02
    password: HFtrcfMdedjFAX8T
#    url: jdbc:mysql://localhost:3306/hundsun02?characterEncoding=utf8&serverTimezone=GMT%2b8
#    username: root
#    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filter:
        config:
          enabled: true
        stat:
          enabled: true
      filters: stat,wall,slf4j
      initial-size: 5
      max-active: 20
      stat-view-servlet:
        allow: 127.0.0.1
        login-username: root
        login-password: 123456
        reset-enable: true
      web-stat-filter:
        enabled: true
        exclusions: .js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*
        session-stat-enable: true
        session-stat-max-count: 100
        url-pattern: /*
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB


minio:
  endpoint: http://8.137.53.253:9000
  bucketName: imgocr
  accessKey: C4RdB4eytLOl7SJRf5qi
  secretKey: GRHwetreXgu2lKZUxctGgrg5JkMwUxQL9Cl5zAGj

logging:
  level: #指定级别
    com.example:
      info
  file:
    name: ./log/server.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      file-name-pattern: server.%d.%i.log

baidu:
  APIkey: dRzeeE2kKkC10kb5WrLj0CFC
  Secretkey: Gy2gBGX2UNgo1Q89xbnL3Z1AdMlgNQkB
#写模型的url地址
modeService:
  ocrMode: http://127.0.0.1:8866/predict/ch_pp_ocrv3